/* imports.c -- GENERATED by runtime/tools/gen_imports.py; do not edit.
 *
 * Every import of libflapfire that no loaded module
 * exports (gl* aside: the GL layer serves those), mapped to the host
 * function or object that serves it: b_* shims for the bionic ABI
 * (bionic_*.c, android_ndk.c, gl_*.c, the port's files), and newlib
 * directly where the two ABIs agree. Declared through asm labels so no
 * C prototype is needed (or can conflict): only the address is taken
 * here. The search over the table is the runtime's imports_lookup.c.
 *
 * Weak imports bound to NULL on purpose: none.
 * MIT.
 */
#include "imports.h"

extern const char sym___errno[] __asm__("__errno");
extern const char sym_b___android_log_print[] __asm__("b___android_log_print");
extern const char sym_b___cxa_atexit[] __asm__("b___cxa_atexit");
extern const char sym_b___cxa_finalize[] __asm__("b___cxa_finalize");
extern const char sym_b___gnu_Unwind_Find_exidx[] __asm__("b___gnu_Unwind_Find_exidx");
extern const char sym_b___sF[] __asm__("b___sF");
extern const char sym_b___stack_chk_fail[] __asm__("b___stack_chk_fail");
extern const char sym_b___stack_chk_guard[] __asm__("b___stack_chk_guard");
extern const char sym_b__ctype_[] __asm__("b__ctype_");
extern const char sym_b_abort[] __asm__("b_abort");
extern const char sym_b_btowc[] __asm__("b_btowc");
extern const char sym_b_fclose[] __asm__("b_fclose");
extern const char sym_b_fdopen[] __asm__("b_fdopen");
extern const char sym_b_fflush[] __asm__("b_fflush");
extern const char sym_b_floor[] __asm__("b_floor");
extern const char sym_b_fopen[] __asm__("b_fopen");
extern const char sym_b_fputc[] __asm__("b_fputc");
extern const char sym_b_fputs[] __asm__("b_fputs");
extern const char sym_b_fread[] __asm__("b_fread");
extern const char sym_b_fseek[] __asm__("b_fseek");
extern const char sym_b_fstat[] __asm__("b_fstat");
extern const char sym_b_ftell[] __asm__("b_ftell");
extern const char sym_b_fwrite[] __asm__("b_fwrite");
extern const char sym_b_getc[] __asm__("b_getc");
extern const char sym_b_gettimeofday[] __asm__("b_gettimeofday");
extern const char sym_b_getwc[] __asm__("b_getwc");
extern const char sym_b_ioctl[] __asm__("b_ioctl");
extern const char sym_b_lseek[] __asm__("b_lseek");
extern const char sym_b_mbrtowc[] __asm__("b_mbrtowc");
extern const char sym_b_memcpy[] __asm__("b_memcpy");
extern const char sym_b_memmove[] __asm__("b_memmove");
extern const char sym_b_memset[] __asm__("b_memset");
extern const char sym_b_poll[] __asm__("b_poll");
extern const char sym_b_pthread_cond_broadcast[] __asm__("b_pthread_cond_broadcast");
extern const char sym_b_pthread_cond_destroy[] __asm__("b_pthread_cond_destroy");
extern const char sym_b_pthread_cond_signal[] __asm__("b_pthread_cond_signal");
extern const char sym_b_pthread_cond_wait[] __asm__("b_pthread_cond_wait");
extern const char sym_b_pthread_getspecific[] __asm__("b_pthread_getspecific");
extern const char sym_b_pthread_key_create[] __asm__("b_pthread_key_create");
extern const char sym_b_pthread_key_delete[] __asm__("b_pthread_key_delete");
extern const char sym_b_pthread_mutex_lock[] __asm__("b_pthread_mutex_lock");
extern const char sym_b_pthread_mutex_unlock[] __asm__("b_pthread_mutex_unlock");
extern const char sym_b_pthread_once[] __asm__("b_pthread_once");
extern const char sym_b_pthread_setspecific[] __asm__("b_pthread_setspecific");
extern const char sym_b_putc[] __asm__("b_putc");
extern const char sym_b_putwc[] __asm__("b_putwc");
extern const char sym_b_raise[] __asm__("b_raise");
extern const char sym_b_read[] __asm__("b_read");
extern const char sym_b_round[] __asm__("b_round");
extern const char sym_b_setlocale[] __asm__("b_setlocale");
extern const char sym_b_setvbuf[] __asm__("b_setvbuf");
extern const char sym_b_sprintf[] __asm__("b_sprintf");
extern const char sym_b_sqrt[] __asm__("b_sqrt");
extern const char sym_b_strerror[] __asm__("b_strerror");
extern const char sym_b_strftime[] __asm__("b_strftime");
extern const char sym_b_syscall[] __asm__("b_syscall");
extern const char sym_b_ungetc[] __asm__("b_ungetc");
extern const char sym_b_ungetwc[] __asm__("b_ungetwc");
extern const char sym_b_vsprintf[] __asm__("b_vsprintf");
extern const char sym_b_wcrtomb[] __asm__("b_wcrtomb");
extern const char sym_b_wcsftime[] __asm__("b_wcsftime");
extern const char sym_b_wctob[] __asm__("b_wctob");
extern const char sym_b_write[] __asm__("b_write");
extern const char sym_b_writev[] __asm__("b_writev");
extern const char sym_fmodf[] __asm__("fmodf");
extern const char sym_free[] __asm__("free");
extern const char sym_iswctype[] __asm__("iswctype");
extern const char sym_malloc[] __asm__("malloc");
extern const char sym_memchr[] __asm__("memchr");
extern const char sym_memcmp[] __asm__("memcmp");
extern const char sym_pow[] __asm__("pow");
extern const char sym_powf[] __asm__("powf");
extern const char sym_realloc[] __asm__("realloc");
extern const char sym_sinf[] __asm__("sinf");
extern const char sym_sscanf[] __asm__("sscanf");
extern const char sym_strcmp[] __asm__("strcmp");
extern const char sym_strcoll[] __asm__("strcoll");
extern const char sym_strcpy[] __asm__("strcpy");
extern const char sym_strlen[] __asm__("strlen");
extern const char sym_strncmp[] __asm__("strncmp");
extern const char sym_strtod[] __asm__("strtod");
extern const char sym_strxfrm[] __asm__("strxfrm");
extern const char sym_towlower[] __asm__("towlower");
extern const char sym_towupper[] __asm__("towupper");
extern const char sym_wcscoll[] __asm__("wcscoll");
extern const char sym_wcslen[] __asm__("wcslen");
extern const char sym_wcsxfrm[] __asm__("wcsxfrm");
extern const char sym_wctype[] __asm__("wctype");
extern const char sym_wmemchr[] __asm__("wmemchr");
extern const char sym_wmemcmp[] __asm__("wmemcmp");
extern const char sym_wmemcpy[] __asm__("wmemcpy");
extern const char sym_wmemmove[] __asm__("wmemmove");
extern const char sym_wmemset[] __asm__("wmemset");

DynLibFunction dcr_imports[] = {
    {"__android_log_print", (uintptr_t)sym_b___android_log_print},
    {"__cxa_atexit", (uintptr_t)sym_b___cxa_atexit},
    {"__cxa_finalize", (uintptr_t)sym_b___cxa_finalize},
    {"__errno", (uintptr_t)sym___errno},
    {"__gnu_Unwind_Find_exidx", (uintptr_t)sym_b___gnu_Unwind_Find_exidx},
    {"__sF", (uintptr_t)sym_b___sF},
    {"__stack_chk_fail", (uintptr_t)sym_b___stack_chk_fail},
    {"__stack_chk_guard", (uintptr_t)sym_b___stack_chk_guard},
    {"_ctype_", (uintptr_t)sym_b__ctype_},
    {"abort", (uintptr_t)sym_b_abort},
    {"btowc", (uintptr_t)sym_b_btowc},
    {"fclose", (uintptr_t)sym_b_fclose},
    {"fdopen", (uintptr_t)sym_b_fdopen},
    {"fflush", (uintptr_t)sym_b_fflush},
    {"floor", (uintptr_t)sym_b_floor},
    {"fmodf", (uintptr_t)sym_fmodf},
    {"fopen", (uintptr_t)sym_b_fopen},
    {"fputc", (uintptr_t)sym_b_fputc},
    {"fputs", (uintptr_t)sym_b_fputs},
    {"fread", (uintptr_t)sym_b_fread},
    {"free", (uintptr_t)sym_free},
    {"fseek", (uintptr_t)sym_b_fseek},
    {"fstat", (uintptr_t)sym_b_fstat},
    {"ftell", (uintptr_t)sym_b_ftell},
    {"fwrite", (uintptr_t)sym_b_fwrite},
    {"getc", (uintptr_t)sym_b_getc},
    {"gettimeofday", (uintptr_t)sym_b_gettimeofday},
    {"getwc", (uintptr_t)sym_b_getwc},
    {"ioctl", (uintptr_t)sym_b_ioctl},
    {"iswctype", (uintptr_t)sym_iswctype},
    {"lseek", (uintptr_t)sym_b_lseek},
    {"malloc", (uintptr_t)sym_malloc},
    {"mbrtowc", (uintptr_t)sym_b_mbrtowc},
    {"memchr", (uintptr_t)sym_memchr},
    {"memcmp", (uintptr_t)sym_memcmp},
    {"memcpy", (uintptr_t)sym_b_memcpy},
    {"memmove", (uintptr_t)sym_b_memmove},
    {"memset", (uintptr_t)sym_b_memset},
    {"poll", (uintptr_t)sym_b_poll},
    {"pow", (uintptr_t)sym_pow},
    {"powf", (uintptr_t)sym_powf},
    {"pthread_cond_broadcast", (uintptr_t)sym_b_pthread_cond_broadcast},
    {"pthread_cond_destroy", (uintptr_t)sym_b_pthread_cond_destroy},
    {"pthread_cond_signal", (uintptr_t)sym_b_pthread_cond_signal},
    {"pthread_cond_wait", (uintptr_t)sym_b_pthread_cond_wait},
    {"pthread_getspecific", (uintptr_t)sym_b_pthread_getspecific},
    {"pthread_key_create", (uintptr_t)sym_b_pthread_key_create},
    {"pthread_key_delete", (uintptr_t)sym_b_pthread_key_delete},
    {"pthread_mutex_lock", (uintptr_t)sym_b_pthread_mutex_lock},
    {"pthread_mutex_unlock", (uintptr_t)sym_b_pthread_mutex_unlock},
    {"pthread_once", (uintptr_t)sym_b_pthread_once},
    {"pthread_setspecific", (uintptr_t)sym_b_pthread_setspecific},
    {"putc", (uintptr_t)sym_b_putc},
    {"putwc", (uintptr_t)sym_b_putwc},
    {"raise", (uintptr_t)sym_b_raise},
    {"read", (uintptr_t)sym_b_read},
    {"realloc", (uintptr_t)sym_realloc},
    {"round", (uintptr_t)sym_b_round},
    {"setlocale", (uintptr_t)sym_b_setlocale},
    {"setvbuf", (uintptr_t)sym_b_setvbuf},
    {"sinf", (uintptr_t)sym_sinf},
    {"sprintf", (uintptr_t)sym_b_sprintf},
    {"sqrt", (uintptr_t)sym_b_sqrt},
    {"sscanf", (uintptr_t)sym_sscanf},
    {"strcmp", (uintptr_t)sym_strcmp},
    {"strcoll", (uintptr_t)sym_strcoll},
    {"strcpy", (uintptr_t)sym_strcpy},
    {"strerror", (uintptr_t)sym_b_strerror},
    {"strftime", (uintptr_t)sym_b_strftime},
    {"strlen", (uintptr_t)sym_strlen},
    {"strncmp", (uintptr_t)sym_strncmp},
    {"strtod", (uintptr_t)sym_strtod},
    {"strxfrm", (uintptr_t)sym_strxfrm},
    {"syscall", (uintptr_t)sym_b_syscall},
    {"towlower", (uintptr_t)sym_towlower},
    {"towupper", (uintptr_t)sym_towupper},
    {"ungetc", (uintptr_t)sym_b_ungetc},
    {"ungetwc", (uintptr_t)sym_b_ungetwc},
    {"vsprintf", (uintptr_t)sym_b_vsprintf},
    {"wcrtomb", (uintptr_t)sym_b_wcrtomb},
    {"wcscoll", (uintptr_t)sym_wcscoll},
    {"wcsftime", (uintptr_t)sym_b_wcsftime},
    {"wcslen", (uintptr_t)sym_wcslen},
    {"wcsxfrm", (uintptr_t)sym_wcsxfrm},
    {"wctob", (uintptr_t)sym_b_wctob},
    {"wctype", (uintptr_t)sym_wctype},
    {"wmemchr", (uintptr_t)sym_wmemchr},
    {"wmemcmp", (uintptr_t)sym_wmemcmp},
    {"wmemcpy", (uintptr_t)sym_wmemcpy},
    {"wmemmove", (uintptr_t)sym_wmemmove},
    {"wmemset", (uintptr_t)sym_wmemset},
    {"write", (uintptr_t)sym_b_write},
    {"writev", (uintptr_t)sym_b_writev},
    {"", 0},
};

int dcr_imports_count = (int)(sizeof(dcr_imports) / sizeof(dcr_imports[0])) - 1;
